### PR TITLE
Craft 4 update changes

### PR DESCRIPTION
**Pull request by honsa**
Just small changes to fit craft4 @matt-west

### CODE REVIEW

**Comment by bossanova808** [comment]
Any progress on this Matt?  Are you planning a Craft 4 version?

**Comment by russclewett-mw** [comment]
Any chance of this being merged in and a Craft 4 version being made available?

**Comment by honsa** [comment]
> @matt-west

you have to ask @matt-west ;)

**Comment by matt-west** [comment]
Hey folks! Apologies for the delay looking at this.

I’ve just release v2.0.1 which includes support for Craft 4 based on this PR. Thanks for contributing!

**Comment by honsa** [comment]
Great to hear, your plugin is used a lot, so keep on track and thanks for your work 👍

**Pull request merged**
